# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LaneMarking.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LaneMarking.proto',
  package='hdmap',
  syntax='proto3',
  serialized_pb=_b('\n\x11LaneMarking.proto\x12\x05hdmap\"9\n\x0bLaneMarking\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08geometry\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\x05\"R\n\x13LaneMarkingPerFrame\x12\x10\n\x08\x66rame_id\x18\x01 \x01(\x05\x12)\n\rlane_markings\x18\x02 \x03(\x0b\x32\x12.hdmap.LaneMarking\"b\n\x15LaneMarkingPerCapture\x12\x10\n\x08scene_id\x18\x01 \x01(\t\x12\x37\n\x13lane_marking_frames\x18\x02 \x03(\x0b\x32\x1a.hdmap.LaneMarkingPerFrameb\x06proto3')
)




_LANEMARKING = _descriptor.Descriptor(
  name='LaneMarking',
  full_name='hdmap.LaneMarking',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='hdmap.LaneMarking.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='hdmap.LaneMarking.geometry', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='hdmap.LaneMarking.type', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=85,
)


_LANEMARKINGPERFRAME = _descriptor.Descriptor(
  name='LaneMarkingPerFrame',
  full_name='hdmap.LaneMarkingPerFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='frame_id', full_name='hdmap.LaneMarkingPerFrame.frame_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_markings', full_name='hdmap.LaneMarkingPerFrame.lane_markings', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=169,
)


_LANEMARKINGPERCAPTURE = _descriptor.Descriptor(
  name='LaneMarkingPerCapture',
  full_name='hdmap.LaneMarkingPerCapture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='hdmap.LaneMarkingPerCapture.scene_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lane_marking_frames', full_name='hdmap.LaneMarkingPerCapture.lane_marking_frames', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=269,
)

_LANEMARKINGPERFRAME.fields_by_name['lane_markings'].message_type = _LANEMARKING
_LANEMARKINGPERCAPTURE.fields_by_name['lane_marking_frames'].message_type = _LANEMARKINGPERFRAME
DESCRIPTOR.message_types_by_name['LaneMarking'] = _LANEMARKING
DESCRIPTOR.message_types_by_name['LaneMarkingPerFrame'] = _LANEMARKINGPERFRAME
DESCRIPTOR.message_types_by_name['LaneMarkingPerCapture'] = _LANEMARKINGPERCAPTURE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LaneMarking = _reflection.GeneratedProtocolMessageType('LaneMarking', (_message.Message,), dict(
  DESCRIPTOR = _LANEMARKING,
  __module__ = 'LaneMarking_pb2'
  # @@protoc_insertion_point(class_scope:hdmap.LaneMarking)
  ))
_sym_db.RegisterMessage(LaneMarking)

LaneMarkingPerFrame = _reflection.GeneratedProtocolMessageType('LaneMarkingPerFrame', (_message.Message,), dict(
  DESCRIPTOR = _LANEMARKINGPERFRAME,
  __module__ = 'LaneMarking_pb2'
  # @@protoc_insertion_point(class_scope:hdmap.LaneMarkingPerFrame)
  ))
_sym_db.RegisterMessage(LaneMarkingPerFrame)

LaneMarkingPerCapture = _reflection.GeneratedProtocolMessageType('LaneMarkingPerCapture', (_message.Message,), dict(
  DESCRIPTOR = _LANEMARKINGPERCAPTURE,
  __module__ = 'LaneMarking_pb2'
  # @@protoc_insertion_point(class_scope:hdmap.LaneMarkingPerCapture)
  ))
_sym_db.RegisterMessage(LaneMarkingPerCapture)


# @@protoc_insertion_point(module_scope)
