# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SourceInfo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SourceInfo.proto',
  package='source',
  syntax='proto3',
  serialized_pb=_b('\n\x10SourceInfo.proto\x12\x06source\"x\n\x08GPSPoint\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07gpstime\x18\x02 \x01(\x03\x12\x0f\n\x07heading\x18\x03 \x01(\x01\x12\r\n\x05speed\x18\x04 \x01(\x01\x12\x10\n\x08\x61\x63\x63uracy\x18\x05 \x01(\x01\x12\x0b\n\x03sum\x18\x06 \x01(\x05\x12\x10\n\x08geometry\x18\x07 \x01(\t\"^\n\x07GPSInfo\x12\x10\n\x08scene_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12\x1d\n\x03pts\x18\x03 \x03(\x0b\x32\x10.source.GPSPoint\x12\x0f\n\x07version\x18\x04 \x01(\t\"7\n\x07IMUInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08scene_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\"G\n\tVideoInfo\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08scene_id\x18\x02 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\tb\x06proto3')
)




_GPSPOINT = _descriptor.Descriptor(
  name='GPSPoint',
  full_name='source.GPSPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='source.GPSPoint.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpstime', full_name='source.GPSPoint.gpstime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heading', full_name='source.GPSPoint.heading', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='speed', full_name='source.GPSPoint.speed', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accuracy', full_name='source.GPSPoint.accuracy', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sum', full_name='source.GPSPoint.sum', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='geometry', full_name='source.GPSPoint.geometry', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=148,
)


_GPSINFO = _descriptor.Descriptor(
  name='GPSInfo',
  full_name='source.GPSInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='source.GPSInfo.scene_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='source.GPSInfo.device_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pts', full_name='source.GPSInfo.pts', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='version', full_name='source.GPSInfo.version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=244,
)


_IMUINFO = _descriptor.Descriptor(
  name='IMUInfo',
  full_name='source.IMUInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='source.IMUInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='source.IMUInfo.scene_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='source.IMUInfo.device', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=301,
)


_VIDEOINFO = _descriptor.Descriptor(
  name='VideoInfo',
  full_name='source.VideoInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='source.VideoInfo.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='source.VideoInfo.scene_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device', full_name='source.VideoInfo.device', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='path', full_name='source.VideoInfo.path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=374,
)

_GPSINFO.fields_by_name['pts'].message_type = _GPSPOINT
DESCRIPTOR.message_types_by_name['GPSPoint'] = _GPSPOINT
DESCRIPTOR.message_types_by_name['GPSInfo'] = _GPSINFO
DESCRIPTOR.message_types_by_name['IMUInfo'] = _IMUINFO
DESCRIPTOR.message_types_by_name['VideoInfo'] = _VIDEOINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GPSPoint = _reflection.GeneratedProtocolMessageType('GPSPoint', (_message.Message,), dict(
  DESCRIPTOR = _GPSPOINT,
  __module__ = 'SourceInfo_pb2'
  # @@protoc_insertion_point(class_scope:source.GPSPoint)
  ))
_sym_db.RegisterMessage(GPSPoint)

GPSInfo = _reflection.GeneratedProtocolMessageType('GPSInfo', (_message.Message,), dict(
  DESCRIPTOR = _GPSINFO,
  __module__ = 'SourceInfo_pb2'
  # @@protoc_insertion_point(class_scope:source.GPSInfo)
  ))
_sym_db.RegisterMessage(GPSInfo)

IMUInfo = _reflection.GeneratedProtocolMessageType('IMUInfo', (_message.Message,), dict(
  DESCRIPTOR = _IMUINFO,
  __module__ = 'SourceInfo_pb2'
  # @@protoc_insertion_point(class_scope:source.IMUInfo)
  ))
_sym_db.RegisterMessage(IMUInfo)

VideoInfo = _reflection.GeneratedProtocolMessageType('VideoInfo', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOINFO,
  __module__ = 'SourceInfo_pb2'
  # @@protoc_insertion_point(class_scope:source.VideoInfo)
  ))
_sym_db.RegisterMessage(VideoInfo)


# @@protoc_insertion_point(module_scope)
