// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Divider.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "Divider.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace hdmap {
class DividerDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<Divider>
     _instance;
} _Divider_default_instance_;
class DividerPerFrameDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DividerPerFrame>
     _instance;
} _DividerPerFrame_default_instance_;
class DividerPerCaptureDefaultTypeInternal {
public:
 ::google::protobuf::internal::ExplicitlyConstructed<DividerPerCapture>
     _instance;
} _DividerPerCapture_default_instance_;

namespace protobuf_Divider_2eproto {


namespace {

::google::protobuf::Metadata file_level_metadata[3];

}  // namespace

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTableField
    const TableStruct::entries[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  {0, 0, 0, ::google::protobuf::internal::kInvalidMask, 0, 0},
};

PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::AuxillaryParseTableField
    const TableStruct::aux[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ::google::protobuf::internal::AuxillaryParseTableField(),
};
PROTOBUF_CONSTEXPR_VAR ::google::protobuf::internal::ParseTable const
    TableStruct::schema[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
  { NULL, NULL, 0, -1, -1, -1, -1, NULL, false },
};

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Divider, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Divider, id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Divider, geometry_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Divider, color_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Divider, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Divider, occlusion_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DividerPerFrame, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DividerPerFrame, frame_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DividerPerFrame, dividers_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DividerPerCapture, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DividerPerCapture, scene_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DividerPerCapture, divider_frames_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(Divider)},
  { 10, -1, sizeof(DividerPerFrame)},
  { 17, -1, sizeof(DividerPerCapture)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&_Divider_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_DividerPerFrame_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&_DividerPerCapture_default_instance_),
};

namespace {

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "Divider.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

}  // namespace
void TableStruct::InitDefaultsImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::InitProtobufDefaults();
  _Divider_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_Divider_default_instance_);_DividerPerFrame_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_DividerPerFrame_default_instance_);_DividerPerCapture_default_instance_._instance.DefaultConstruct();
  ::google::protobuf::internal::OnShutdownDestroyMessage(
      &_DividerPerCapture_default_instance_);}

void InitDefaults() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &TableStruct::InitDefaultsImpl);
}
namespace {
void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rDivider.proto\022\005hdmap\"W\n\007Divider\022\n\n\002id\030"
      "\001 \001(\005\022\020\n\010geometry\030\002 \001(\t\022\r\n\005color\030\003 \001(\005\022\014"
      "\n\004type\030\004 \001(\005\022\021\n\tocclusion\030\005 \001(\005\"E\n\017Divid"
      "erPerFrame\022\020\n\010frame_id\030\001 \001(\005\022 \n\010dividers"
      "\030\002 \003(\0132\016.hdmap.Divider\"U\n\021DividerPerCapt"
      "ure\022\020\n\010scene_id\030\001 \001(\t\022.\n\016divider_frames\030"
      "\002 \003(\0132\026.hdmap.DividerPerFrameb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 277);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "Divider.proto", &protobuf_RegisterTypes);
}
} // anonymous namespace

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;

}  // namespace protobuf_Divider_2eproto


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Divider::kIdFieldNumber;
const int Divider::kGeometryFieldNumber;
const int Divider::kColorFieldNumber;
const int Divider::kTypeFieldNumber;
const int Divider::kOcclusionFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Divider::Divider()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Divider_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap.Divider)
}
Divider::Divider(const Divider& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  geometry_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.geometry().size() > 0) {
    geometry_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.geometry_);
  }
  ::memcpy(&id_, &from.id_,
    static_cast<size_t>(reinterpret_cast<char*>(&occlusion_) -
    reinterpret_cast<char*>(&id_)) + sizeof(occlusion_));
  // @@protoc_insertion_point(copy_constructor:hdmap.Divider)
}

void Divider::SharedCtor() {
  geometry_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&occlusion_) -
      reinterpret_cast<char*>(&id_)) + sizeof(occlusion_));
  _cached_size_ = 0;
}

Divider::~Divider() {
  // @@protoc_insertion_point(destructor:hdmap.Divider)
  SharedDtor();
}

void Divider::SharedDtor() {
  geometry_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Divider::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Divider::descriptor() {
  protobuf_Divider_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Divider_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Divider& Divider::default_instance() {
  protobuf_Divider_2eproto::InitDefaults();
  return *internal_default_instance();
}

Divider* Divider::New(::google::protobuf::Arena* arena) const {
  Divider* n = new Divider;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Divider::Clear() {
// @@protoc_insertion_point(message_clear_start:hdmap.Divider)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  geometry_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&occlusion_) -
      reinterpret_cast<char*>(&id_)) + sizeof(occlusion_));
  _internal_metadata_.Clear();
}

bool Divider::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap.Divider)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string geometry = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_geometry()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->geometry().data(), static_cast<int>(this->geometry().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "hdmap.Divider.geometry"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 color = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &color_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 type = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 occlusion = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &occlusion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap.Divider)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap.Divider)
  return false;
#undef DO_
}

void Divider::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap.Divider)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->id(), output);
  }

  // string geometry = 2;
  if (this->geometry().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->geometry().data(), static_cast<int>(this->geometry().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hdmap.Divider.geometry");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->geometry(), output);
  }

  // int32 color = 3;
  if (this->color() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->color(), output);
  }

  // int32 type = 4;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->type(), output);
  }

  // int32 occlusion = 5;
  if (this->occlusion() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->occlusion(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap.Divider)
}

::google::protobuf::uint8* Divider::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hdmap.Divider)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 id = 1;
  if (this->id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->id(), target);
  }

  // string geometry = 2;
  if (this->geometry().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->geometry().data(), static_cast<int>(this->geometry().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hdmap.Divider.geometry");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->geometry(), target);
  }

  // int32 color = 3;
  if (this->color() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->color(), target);
  }

  // int32 type = 4;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->type(), target);
  }

  // int32 occlusion = 5;
  if (this->occlusion() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->occlusion(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap.Divider)
  return target;
}

size_t Divider::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hdmap.Divider)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string geometry = 2;
  if (this->geometry().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->geometry());
  }

  // int32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->id());
  }

  // int32 color = 3;
  if (this->color() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->color());
  }

  // int32 type = 4;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  // int32 occlusion = 5;
  if (this->occlusion() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->occlusion());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Divider::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hdmap.Divider)
  GOOGLE_DCHECK_NE(&from, this);
  const Divider* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Divider>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hdmap.Divider)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hdmap.Divider)
    MergeFrom(*source);
  }
}

void Divider::MergeFrom(const Divider& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hdmap.Divider)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.geometry().size() > 0) {

    geometry_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.geometry_);
  }
  if (from.id() != 0) {
    set_id(from.id());
  }
  if (from.color() != 0) {
    set_color(from.color());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.occlusion() != 0) {
    set_occlusion(from.occlusion());
  }
}

void Divider::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hdmap.Divider)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Divider::CopyFrom(const Divider& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hdmap.Divider)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Divider::IsInitialized() const {
  return true;
}

void Divider::Swap(Divider* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Divider::InternalSwap(Divider* other) {
  using std::swap;
  geometry_.Swap(&other->geometry_);
  swap(id_, other->id_);
  swap(color_, other->color_);
  swap(type_, other->type_);
  swap(occlusion_, other->occlusion_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Divider::GetMetadata() const {
  protobuf_Divider_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Divider_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Divider

// int32 id = 1;
void Divider::clear_id() {
  id_ = 0;
}
::google::protobuf::int32 Divider::id() const {
  // @@protoc_insertion_point(field_get:hdmap.Divider.id)
  return id_;
}
void Divider::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:hdmap.Divider.id)
}

// string geometry = 2;
void Divider::clear_geometry() {
  geometry_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& Divider::geometry() const {
  // @@protoc_insertion_point(field_get:hdmap.Divider.geometry)
  return geometry_.GetNoArena();
}
void Divider::set_geometry(const ::std::string& value) {
  
  geometry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hdmap.Divider.geometry)
}
#if LANG_CXX11
void Divider::set_geometry(::std::string&& value) {
  
  geometry_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hdmap.Divider.geometry)
}
#endif
void Divider::set_geometry(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  geometry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hdmap.Divider.geometry)
}
void Divider::set_geometry(const char* value, size_t size) {
  
  geometry_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hdmap.Divider.geometry)
}
::std::string* Divider::mutable_geometry() {
  
  // @@protoc_insertion_point(field_mutable:hdmap.Divider.geometry)
  return geometry_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* Divider::release_geometry() {
  // @@protoc_insertion_point(field_release:hdmap.Divider.geometry)
  
  return geometry_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void Divider::set_allocated_geometry(::std::string* geometry) {
  if (geometry != NULL) {
    
  } else {
    
  }
  geometry_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), geometry);
  // @@protoc_insertion_point(field_set_allocated:hdmap.Divider.geometry)
}

// int32 color = 3;
void Divider::clear_color() {
  color_ = 0;
}
::google::protobuf::int32 Divider::color() const {
  // @@protoc_insertion_point(field_get:hdmap.Divider.color)
  return color_;
}
void Divider::set_color(::google::protobuf::int32 value) {
  
  color_ = value;
  // @@protoc_insertion_point(field_set:hdmap.Divider.color)
}

// int32 type = 4;
void Divider::clear_type() {
  type_ = 0;
}
::google::protobuf::int32 Divider::type() const {
  // @@protoc_insertion_point(field_get:hdmap.Divider.type)
  return type_;
}
void Divider::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:hdmap.Divider.type)
}

// int32 occlusion = 5;
void Divider::clear_occlusion() {
  occlusion_ = 0;
}
::google::protobuf::int32 Divider::occlusion() const {
  // @@protoc_insertion_point(field_get:hdmap.Divider.occlusion)
  return occlusion_;
}
void Divider::set_occlusion(::google::protobuf::int32 value) {
  
  occlusion_ = value;
  // @@protoc_insertion_point(field_set:hdmap.Divider.occlusion)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DividerPerFrame::kFrameIdFieldNumber;
const int DividerPerFrame::kDividersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DividerPerFrame::DividerPerFrame()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Divider_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap.DividerPerFrame)
}
DividerPerFrame::DividerPerFrame(const DividerPerFrame& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      dividers_(from.dividers_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  frame_id_ = from.frame_id_;
  // @@protoc_insertion_point(copy_constructor:hdmap.DividerPerFrame)
}

void DividerPerFrame::SharedCtor() {
  frame_id_ = 0;
  _cached_size_ = 0;
}

DividerPerFrame::~DividerPerFrame() {
  // @@protoc_insertion_point(destructor:hdmap.DividerPerFrame)
  SharedDtor();
}

void DividerPerFrame::SharedDtor() {
}

void DividerPerFrame::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DividerPerFrame::descriptor() {
  protobuf_Divider_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Divider_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DividerPerFrame& DividerPerFrame::default_instance() {
  protobuf_Divider_2eproto::InitDefaults();
  return *internal_default_instance();
}

DividerPerFrame* DividerPerFrame::New(::google::protobuf::Arena* arena) const {
  DividerPerFrame* n = new DividerPerFrame;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DividerPerFrame::Clear() {
// @@protoc_insertion_point(message_clear_start:hdmap.DividerPerFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  dividers_.Clear();
  frame_id_ = 0;
  _internal_metadata_.Clear();
}

bool DividerPerFrame::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap.DividerPerFrame)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 frame_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &frame_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .hdmap.Divider dividers = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_dividers()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap.DividerPerFrame)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap.DividerPerFrame)
  return false;
#undef DO_
}

void DividerPerFrame::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap.DividerPerFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 frame_id = 1;
  if (this->frame_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->frame_id(), output);
  }

  // repeated .hdmap.Divider dividers = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->dividers_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->dividers(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap.DividerPerFrame)
}

::google::protobuf::uint8* DividerPerFrame::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hdmap.DividerPerFrame)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 frame_id = 1;
  if (this->frame_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->frame_id(), target);
  }

  // repeated .hdmap.Divider dividers = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->dividers_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->dividers(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap.DividerPerFrame)
  return target;
}

size_t DividerPerFrame::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hdmap.DividerPerFrame)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .hdmap.Divider dividers = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->dividers_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dividers(static_cast<int>(i)));
    }
  }

  // int32 frame_id = 1;
  if (this->frame_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->frame_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DividerPerFrame::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hdmap.DividerPerFrame)
  GOOGLE_DCHECK_NE(&from, this);
  const DividerPerFrame* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DividerPerFrame>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hdmap.DividerPerFrame)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hdmap.DividerPerFrame)
    MergeFrom(*source);
  }
}

void DividerPerFrame::MergeFrom(const DividerPerFrame& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hdmap.DividerPerFrame)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  dividers_.MergeFrom(from.dividers_);
  if (from.frame_id() != 0) {
    set_frame_id(from.frame_id());
  }
}

void DividerPerFrame::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hdmap.DividerPerFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DividerPerFrame::CopyFrom(const DividerPerFrame& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hdmap.DividerPerFrame)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DividerPerFrame::IsInitialized() const {
  return true;
}

void DividerPerFrame::Swap(DividerPerFrame* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DividerPerFrame::InternalSwap(DividerPerFrame* other) {
  using std::swap;
  dividers_.InternalSwap(&other->dividers_);
  swap(frame_id_, other->frame_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DividerPerFrame::GetMetadata() const {
  protobuf_Divider_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Divider_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DividerPerFrame

// int32 frame_id = 1;
void DividerPerFrame::clear_frame_id() {
  frame_id_ = 0;
}
::google::protobuf::int32 DividerPerFrame::frame_id() const {
  // @@protoc_insertion_point(field_get:hdmap.DividerPerFrame.frame_id)
  return frame_id_;
}
void DividerPerFrame::set_frame_id(::google::protobuf::int32 value) {
  
  frame_id_ = value;
  // @@protoc_insertion_point(field_set:hdmap.DividerPerFrame.frame_id)
}

// repeated .hdmap.Divider dividers = 2;
int DividerPerFrame::dividers_size() const {
  return dividers_.size();
}
void DividerPerFrame::clear_dividers() {
  dividers_.Clear();
}
const ::hdmap::Divider& DividerPerFrame::dividers(int index) const {
  // @@protoc_insertion_point(field_get:hdmap.DividerPerFrame.dividers)
  return dividers_.Get(index);
}
::hdmap::Divider* DividerPerFrame::mutable_dividers(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap.DividerPerFrame.dividers)
  return dividers_.Mutable(index);
}
::hdmap::Divider* DividerPerFrame::add_dividers() {
  // @@protoc_insertion_point(field_add:hdmap.DividerPerFrame.dividers)
  return dividers_.Add();
}
::google::protobuf::RepeatedPtrField< ::hdmap::Divider >*
DividerPerFrame::mutable_dividers() {
  // @@protoc_insertion_point(field_mutable_list:hdmap.DividerPerFrame.dividers)
  return &dividers_;
}
const ::google::protobuf::RepeatedPtrField< ::hdmap::Divider >&
DividerPerFrame::dividers() const {
  // @@protoc_insertion_point(field_list:hdmap.DividerPerFrame.dividers)
  return dividers_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DividerPerCapture::kSceneIdFieldNumber;
const int DividerPerCapture::kDividerFramesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DividerPerCapture::DividerPerCapture()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    protobuf_Divider_2eproto::InitDefaults();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:hdmap.DividerPerCapture)
}
DividerPerCapture::DividerPerCapture(const DividerPerCapture& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      divider_frames_(from.divider_frames_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  scene_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.scene_id().size() > 0) {
    scene_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.scene_id_);
  }
  // @@protoc_insertion_point(copy_constructor:hdmap.DividerPerCapture)
}

void DividerPerCapture::SharedCtor() {
  scene_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

DividerPerCapture::~DividerPerCapture() {
  // @@protoc_insertion_point(destructor:hdmap.DividerPerCapture)
  SharedDtor();
}

void DividerPerCapture::SharedDtor() {
  scene_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DividerPerCapture::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DividerPerCapture::descriptor() {
  protobuf_Divider_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Divider_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DividerPerCapture& DividerPerCapture::default_instance() {
  protobuf_Divider_2eproto::InitDefaults();
  return *internal_default_instance();
}

DividerPerCapture* DividerPerCapture::New(::google::protobuf::Arena* arena) const {
  DividerPerCapture* n = new DividerPerCapture;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DividerPerCapture::Clear() {
// @@protoc_insertion_point(message_clear_start:hdmap.DividerPerCapture)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  divider_frames_.Clear();
  scene_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool DividerPerCapture::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hdmap.DividerPerCapture)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string scene_id = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_scene_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->scene_id().data(), static_cast<int>(this->scene_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "hdmap.DividerPerCapture.scene_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .hdmap.DividerPerFrame divider_frames = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
                input, add_divider_frames()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hdmap.DividerPerCapture)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hdmap.DividerPerCapture)
  return false;
#undef DO_
}

void DividerPerCapture::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hdmap.DividerPerCapture)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string scene_id = 1;
  if (this->scene_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->scene_id().data(), static_cast<int>(this->scene_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hdmap.DividerPerCapture.scene_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->scene_id(), output);
  }

  // repeated .hdmap.DividerPerFrame divider_frames = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->divider_frames_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->divider_frames(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:hdmap.DividerPerCapture)
}

::google::protobuf::uint8* DividerPerCapture::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hdmap.DividerPerCapture)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string scene_id = 1;
  if (this->scene_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->scene_id().data(), static_cast<int>(this->scene_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hdmap.DividerPerCapture.scene_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->scene_id(), target);
  }

  // repeated .hdmap.DividerPerFrame divider_frames = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->divider_frames_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->divider_frames(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hdmap.DividerPerCapture)
  return target;
}

size_t DividerPerCapture::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hdmap.DividerPerCapture)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .hdmap.DividerPerFrame divider_frames = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->divider_frames_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->divider_frames(static_cast<int>(i)));
    }
  }

  // string scene_id = 1;
  if (this->scene_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->scene_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DividerPerCapture::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hdmap.DividerPerCapture)
  GOOGLE_DCHECK_NE(&from, this);
  const DividerPerCapture* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DividerPerCapture>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hdmap.DividerPerCapture)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hdmap.DividerPerCapture)
    MergeFrom(*source);
  }
}

void DividerPerCapture::MergeFrom(const DividerPerCapture& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hdmap.DividerPerCapture)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  divider_frames_.MergeFrom(from.divider_frames_);
  if (from.scene_id().size() > 0) {

    scene_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.scene_id_);
  }
}

void DividerPerCapture::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hdmap.DividerPerCapture)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DividerPerCapture::CopyFrom(const DividerPerCapture& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hdmap.DividerPerCapture)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DividerPerCapture::IsInitialized() const {
  return true;
}

void DividerPerCapture::Swap(DividerPerCapture* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DividerPerCapture::InternalSwap(DividerPerCapture* other) {
  using std::swap;
  divider_frames_.InternalSwap(&other->divider_frames_);
  scene_id_.Swap(&other->scene_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DividerPerCapture::GetMetadata() const {
  protobuf_Divider_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_Divider_2eproto::file_level_metadata[kIndexInFileMessages];
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DividerPerCapture

// string scene_id = 1;
void DividerPerCapture::clear_scene_id() {
  scene_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DividerPerCapture::scene_id() const {
  // @@protoc_insertion_point(field_get:hdmap.DividerPerCapture.scene_id)
  return scene_id_.GetNoArena();
}
void DividerPerCapture::set_scene_id(const ::std::string& value) {
  
  scene_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hdmap.DividerPerCapture.scene_id)
}
#if LANG_CXX11
void DividerPerCapture::set_scene_id(::std::string&& value) {
  
  scene_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:hdmap.DividerPerCapture.scene_id)
}
#endif
void DividerPerCapture::set_scene_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  scene_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hdmap.DividerPerCapture.scene_id)
}
void DividerPerCapture::set_scene_id(const char* value, size_t size) {
  
  scene_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hdmap.DividerPerCapture.scene_id)
}
::std::string* DividerPerCapture::mutable_scene_id() {
  
  // @@protoc_insertion_point(field_mutable:hdmap.DividerPerCapture.scene_id)
  return scene_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DividerPerCapture::release_scene_id() {
  // @@protoc_insertion_point(field_release:hdmap.DividerPerCapture.scene_id)
  
  return scene_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DividerPerCapture::set_allocated_scene_id(::std::string* scene_id) {
  if (scene_id != NULL) {
    
  } else {
    
  }
  scene_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), scene_id);
  // @@protoc_insertion_point(field_set_allocated:hdmap.DividerPerCapture.scene_id)
}

// repeated .hdmap.DividerPerFrame divider_frames = 2;
int DividerPerCapture::divider_frames_size() const {
  return divider_frames_.size();
}
void DividerPerCapture::clear_divider_frames() {
  divider_frames_.Clear();
}
const ::hdmap::DividerPerFrame& DividerPerCapture::divider_frames(int index) const {
  // @@protoc_insertion_point(field_get:hdmap.DividerPerCapture.divider_frames)
  return divider_frames_.Get(index);
}
::hdmap::DividerPerFrame* DividerPerCapture::mutable_divider_frames(int index) {
  // @@protoc_insertion_point(field_mutable:hdmap.DividerPerCapture.divider_frames)
  return divider_frames_.Mutable(index);
}
::hdmap::DividerPerFrame* DividerPerCapture::add_divider_frames() {
  // @@protoc_insertion_point(field_add:hdmap.DividerPerCapture.divider_frames)
  return divider_frames_.Add();
}
::google::protobuf::RepeatedPtrField< ::hdmap::DividerPerFrame >*
DividerPerCapture::mutable_divider_frames() {
  // @@protoc_insertion_point(field_mutable_list:hdmap.DividerPerCapture.divider_frames)
  return &divider_frames_;
}
const ::google::protobuf::RepeatedPtrField< ::hdmap::DividerPerFrame >&
DividerPerCapture::divider_frames() const {
  // @@protoc_insertion_point(field_list:hdmap.DividerPerCapture.divider_frames)
  return divider_frames_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace hdmap

// @@protoc_insertion_point(global_scope)
